---
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=your-admin-password-base64"
      - "GF_SECURITY_ADMIN_USER=your-admin-username"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
volumes:
  grafana_data:
    name: grafana_data
