apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx # Name of the deployment
  namespace: nginx # Name of the namespace
  labels:
    app: nginx # Name of your application
spec:
  selector:
    matchLabels:
      app: nginx # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: nginx # Name of your application
    spec:
      containers:
        # Containers are the individual pieces of your application that you want
        # to run.
        - name: nginx # Name of the container
          image: nginx:latest # The image you want to run
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "1"
          #   requests:
          #     memory: 256Mi
          #     cpu: "0.2"
          ports:
            - name: http
              containerPort: 80 # The port that your application uses
          volumeMounts:
            # VolumeMounts are the volumes that your application uses.
            - mountPath: /var/www/html # The path that your application uses
              name: nginx-data # Name of the volume
      volumes:
        # Volumes are the persistent storage that your application uses.
        - name: nginx-data # Name of the volume
          persistentVolumeClaim:
            claimName: nginx-pvc # Name of the persistent volume claim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  #type: ClusterIP
  type: ClusterIP
  # ClusterIP means this service can be accessed by any pod in the cluster
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP # optional protocol

