---
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- MENU_VERSION=1.9.9 #optional
      #- PORT_RANGE=30000:30010 #optional
      #- SUBFOLDER=/ #optional
    volumes:
      - /netboot/config:/config
      #- /opt/netboot/assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 80:80
    restart: unless-stopped
