---
- hosts: "*"
  vars:
    NFS_SHARE: <NFS-SHARE>
    MOUNT_POINT: <MOUNT-POINT>
  tasks:
    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present
        update_cache: true
      become: true
    - name: Mount an NFS volume
      ansible.posix.mount:
        src: "{{ NFS_SHARE }}"
        path: "{{ MOUNT_POINT }}"
        opts: rw,sync,hard
        state: mounted
        fstype: nfs
      become: true
