curl -sfL https://get.k3s.io | K3S_TOKEN=3VwqwaDUU2uDVdaBdqCvaA6TsZc8d2TvKhh76PM8kKB6TdV476Pwi5ESirFyFKRi sh -s - server --node-taint CriticalAddonsOnly=true:NoExecute --tls-san=192.168.9.2 --cluster-init

curl -sfL https://get.k3s.io | sh -s - server \
--token=3VwqwaDUU2uDVdaBdqCvaA6TsZc8d2TvKhh76PM8kKB6TdV476Pwi5ESirFyFKRi \
--tls-san cluster-01.hetzner.hochschulte.me --tls-san 192.168.10.2 \
--node-taint CriticalAddonsOnly=true:NoExecute \
--disable traefik \
--disable=servicelb \
--cluster-init

curl -sfL https://get.k3s.io | sh -s - server \
--token=3VwqwaDUU2uDVdaBdqCvaA6TsZc8d2TvKhh76PM8kKB6TdV476Pwi5ESirFyFKRi \
--tls-san cluster-01.hetzner.hochschulte.me --tls-san 192.168.10.2 \
--node-taint CriticalAddonsOnly=true:NoExecute \
--server https://192.168.10.20:6443

curl -sfL https://get.k3s.io | sh -s - agent \
--server https://192.168.10.2:6443 \
--token 3VwqwaDUU2uDVdaBdqCvaA6TsZc8d2TvKhh76PM8kKB6TdV476Pwi5ESirFyFKRi
