---
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tc
    environment:
      - "WEBPASSWORD=your-secret-password-in-base64"
      - "TZ=Europe/Berlin"
    volumes:
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
volumes:
  pihole_data:
    name: pihole_data
  pihole_dnsmasq:
    name: pihole_dnsmasq
