apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-hochschulte-me
  namespace: heimdall
spec:
  secretName: production-hochschulte-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.kube-home-01.hochschulte.me"
  dnsNames:
    - "kube-home-01.hochschulte.me"
    - "*.kube-home-01.hochschulte.me"
