apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure # web or websecure
  routes:
    - match: Host(`longhorn.kube-home-01.hochschulte.me`)
      kind: Rule
      #middlewares:
      #  - name: traefik-dashboard-basicauth
      #    namespace: traefik
      services:
        - name: longhorn-frontend
          kind: Service
          port: 80
  tls:
    secretName: production-hochschulte-me-tls
