---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma_data:/app/data
      #- /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  uptime-kuma_data:
    name: uptime-kuma_data
