---
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    command:
      - "--log=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--providers.file.filename=/etc/traefik/config/config.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      #- "--certificatesresolvers.staging.acme.email=your-letsencrypt-email"
      #- "--certificatesresolvers.staging.acme.storage=/etc/traefik/certs/acme.json"
      #- "--certificatesresolvers.staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      #- "--certificatesresolvers.staging.acme.dnschallenge=true"
      #- "--certificatesresolvers.staging.acme.dnschallenge.provider=cloudflare"
      #- "--certificatesresolvers.staging.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.production.acme.email=your-letsencrypt-email"
      - "--certificatesresolvers.production.acme.storage=/etc/traefik/certs/acme.json"
      - "--certificatesresolvers.production.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.production.acme.dnschallenge=true"
      - "--certificatesresolvers.production.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.production.acme.dnschallenge.resolvers=1.1.1.1:53"
    labels:
      # Dashboard
      - traefik.enable=true
      - "traefik.http.middlewares.simpleAuth.basicAuth.users=your-basisauth-credentials"
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.middlewares=simpleAuth
      #- traefik.http.routers.api.rule=your-dns-address
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=production
      - traefik.http.routers.api.service=api@internal
    environment:
      - "CF_API_EMAIL=your-cloudflare-email"
      - "CF_DNS_API_TOKEN=your-cloudflare-dns-token"
    volumes:
      - /etc/traefik/certs:/etc/traefik/certs
      - /etc/traefik/config:/etc/traefik/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      web:
    restart: unless-stopped
